# Site settings
title: "Operation Homepage"
description: "Get noticed with a one-page website"
url: "https://operationhomepage.com"
cover: "/library/cover.png"
logo: "/library/images/logos/skymse-logo-circle.png"
username: "@OperationHompage"
email: "sos@skymousestudios.com"
location: "Indianapolis, IN • Chattanooga, TN"
color: "#22205F"

# sass/css minify
sass:
  style: compressed

plugins:
  - jekyll-menus
  - jekyll-redirect-from
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name

# Fixes a font awesome issue
webrick:
  headers:
    Access-Control-Allow-Origin: "*"