# Site settings
title: "Operation Homepage"
description: "Get noticed with a one-page website"
url: "https://operationhomepage.com"
cover: "/library/cover.png"
logo: "/library/images/logos/skymse-logo-circle.png"
username: "@OperationHompage"
email: "sos@OperationHompage.com"
location: "Indianapolis, IN • Chattanooga, TN"
color: "#22205F"

# sass/css minify
sass:
  style: compressed

plugins:
  - jekyll-menus
  - jekyll-redirect-from
  - jekyll-sitemap

collections:
  services:
    output: true
    permalink: /:collection/:name
  casestudies:
    output: true
    permalink: /work/:name
  pages:
    output: true
    permalink: /:name
  downloads:
    output: true
    permalink: /downloads/:name